POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlvIiwiaWQiOiI2NmI3NDJhOTIzOWZjNDUxZTA1YTQ0YjkiLCJpYXQiOjE3MjMzOTMyMzcsImV4cCI6MTcyMzM5NjgzN30.dKYOPm7Hs6nUleZzj7byge41uuaakP439wKU--DvrYg

{
    "_id": "5a422a851b54a676234d1712",
    "title": "Nuevo blog de Mario",
    "author": "Mario",
    "url": "https://reactpatterns.com/",
    "likes": 7
}