DELETE http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNjYWlsYW4iLCJpZCI6IjY2YmE3Y2EwMjFmOWFkYWE3NWVhM2RiYSIsImlhdCI6MTcyMzU0MTczNiwiZXhwIjoxNzIzNTQ1MzM2fQ.qU03G9jQhotxhjzT4m9HCx_4qFG0DObI04u3iFQorP8

{
    "id": "66bb1ea9cac6cfd6f41018ee"
}